const MENU_ITEMS = [
  { key: 'navigation', label: 'Navigation', isTitle: true },
  {
    key: 'dashboards',
    label: 'Dashboards',
    isTitle: false,
    icon: 'uil-dashboard',
    badge: { variant: 'success', text: '4' },
    roles: ['Admin'],
    children: [
      {
        key: 'ds-analytics',
        label: 'Analytics',
        url: '/dashboard/analytics',
        icon: 'uil-analysis',
      },
      {
        key: 'ds-newslettersub-manager',
        label: 'Subscription Manager',
        url: '/dashboard/newslettersubscriptions',
        icon: 'uil-newspaper',
      },
      {
        key: 'ds-admin',
        label: 'Admin',
        url: '/dashboard/admin',
        icon: 'uil-users-alt',
      },
    ],
  },
  {
    key: 'civilian-dashboard',
    label: 'Dashboard',
    isTitle: false,
    icon: 'uil-dashboard',
    badge: { variant: 'success', text: '4' },
    roles: ['Civilian'],
    url: '/dashboard/civilian',
  },
  {
    key: 'proprietor-dashboards',
    label: 'Dashboard',
    isTitle: false,
    icon: 'uil-dashboard',
    badge: { variant: 'success', text: '4' },
    roles: ['Proprietor'],
    url: '/dashboard/landlord',
  },
  {
    key: 'activeduty-dashboards',
    label: 'Dashboard',
    isTitle: false,
    icon: 'uil-dashboard',
    badge: { variant: 'success', text: '4' },
    roles: ['Active Duty'],
    url: '/dashboard/military',
  },
  {
    key: 'veteran-dashboards',
    label: 'Dashboard',
    isTitle: false,
    icon: 'uil-dashboard',
    badge: { variant: 'success', text: '4' },
    roles: ['Veteran'],
    url: '/dashboard/military',
  },
  {
    key: 'landlord-dashboards',
    label: 'Dashboards',
    isTitle: false,
    icon: 'uil-dashboard',
    badge: { variant: 'success', text: '4' },
    roles: ['Proprietor'],
    url: '/dashboard/landlord',
  },
  { key: 'rewards', label: 'Rewards', isTitle: true },
  {
    key: 'rewards',
    label: 'Rewards',
    isTitle: false,
    icon: 'uil-gift',
    badge: { variant: 'success', text: '4' },
    url: '/dashboard/rewards',
    roles: ['Proprietor', 'Civilian', 'Active Duty', 'Veteran'],
  },
  { key: 'apps', label: 'Apps', isTitle: true },
  {
    key: 'apps',
    label: 'Apps',
    isTitle: false,
    icon: 'uil-apps',
    badge: { variant: 'success', text: '4' },
    roles: ['Admin', 'Proprietor', 'Civilian', 'Active Duty', 'Veteran'],
    children: [
      {
        key: 'apps-blogs',
        label: 'Blogs',
        isTitle: false,
        icon: 'uil-comment-alt-edit',
        url: '/blogs',
        roles: ['Admin', 'Proprietor', 'Civilian', 'Active Duty', 'Veteran'],
      },
      {
        key: 'apps-podcasts',
        label: 'Podcasts',
        isTitle: false,
        icon: 'uil-microphone',
        url: '/apps/podcast',
        roles: ['Admin', 'Proprietor', 'Civilian', 'Active Duty', 'Veteran'],
      },
      {
        key: 'apps-chat',
        label: 'Chat',
        isTitle: false,
        icon: 'uil-comments-alt',
        url: '/apps/chat',
        roles: ['Admin', 'Proprietor', 'Civilian', 'Active Duty', 'Veteran'],
      },
      {
        key: 'apps-chat',
        label: 'Video Chat',
        isTitle: false,
        icon: 'uil-video',
        url: '/apps/videochat',
        roles: ['Admin', 'Proprietor', 'Civilian', 'Active Duty', 'Veteran'],
      },
      {
        key: 'apps-locations',
        label: 'Locations',
        isTitle: false,
        icon: 'uil-map',
        url: '/apps/locations',
        roles: ['Admin', 'Proprietor', 'Civilian', 'Active Duty', 'Veteran'],
      },
      {
        key: 'apps-file-manager',
        label: 'File Manager',
        isTitle: false,
        icon: 'uil-folder-plus',
        url: '/apps/file',
        roles: ['Admin'],
      },
      {
        key: 'apps-newsletters',
        label: 'Newsletter',
        isTitle: false,
        icon: 'uil-newspaper',
        url: '/newsletters',
        roles: ['Admin'],
      },
    ],
  },
  { key: 'faq', label: 'FAQ', isTitle: true },
  {
    key: 'faq',
    label: 'FAQ',
    isTitle: false,
    icon: 'uil-question-circle',
    badge: { variant: 'success', text: '4' },
    roles: ['Admin'],
    children: [
      {
        key: 'faq-add',
        label: 'Create New FAQ',
        url: '/faq/new',
        icon: 'uil-comment-alt-edit',
      },
      {
        key: 'faq-edit',
        label: 'Admin View',
        url: '/faq/admin',
        icon: 'uil-question-circle',
      },
    ],
  },
  { key: 'survey', label: 'Survey', isTitle: true },
  {
    key: 'survey',
    label: 'Surveys',
    isTitle: false,
    icon: 'uil-file-blank',
    badge: { variant: 'success', text: '4' },
    roles: ['Admin'],
    children: [
      {
        key: 'surveys',
        label: 'View Surveys',
        url: '/surveys',
        icon: 'uil-file-blank',
      },
      {
        key: 'survey-builder',
        label: 'Add Survey Question',
        url: '/survey/question/new',
        icon: 'uil-comment-alt-edit',
      },
      {
        key: 'survey-question-view',
        label: 'View Survey Questions',
        url: '/survey/question/view',
        icon: 'uil-question-circle',
      },
      {
        key: 'survey-analytics',
        label: 'Survey Analytics',
        url: '/survey/analytics',
        icon: 'uil-analysis',
      },
    ],
  },
];

export default MENU_ITEMS;
